export const ROUTES = {
  home: "/",
  categories: "/genel-kultur-kategorileri",
  contentHub: "/sorular-ve-cevaplar",
  genelKulturSorulari: "/genel-kultur-sorulari",
  genelKulturSorulariCevaplari: "/genel-kultur-sorulari-ve-cevaplari",
  genelKulturTesti: "/genel-kultur-testi",
  zorGenelKulturSorulari: "/zor-genel-kultur-sorulari",
  tarihSorulari: "/tarih-sorulari",
  tarihSorulariCevaplari: "/tarih-sorulari-ve-cevaplari",
  bilimSorulari: "/bilim-sorulari",
  bilimSorulariCevaplari: "/bilim-sorulari-ve-cevaplari",
  sanatSorulari: "/sanat-sorulari",
  sanatSorulariCevaplari: "/sanat-sorulari-ve-cevaplari",
  game: "/genel-kultur-oyunu",
  results: "/sonuclar",
  about: "/hakkimizda",
  contact: "/iletisim",
  privacy: "/gizlilik-politikasi",
  cookies: "/cerez-politikasi",
  contentPolicy: "/icerik-politikasi",
  adsDisclosure: "/reklam-bilgilendirmesi",
  terms: "/kullanim-kosullari",
} as const;

export const LEGACY_ROUTES = {
  categories: "/categories",
  game: "/game",
  results: "/results",
  about: "/about",
  contact: "/contact",
  privacy: "/privacy",
  terms: "/terms",
} as const;
