export const ROUTES = {
  home: "/",
  categories: "/genel-kultur-kategorileri",
  kpssList: "/kpss-tarih-konulari",
  profile: "/profil",
  contentHub: "/sorular-ve-cevaplar",
  genelKulturSorulari: "/genel-kultur-sorulari",
  genelKulturSorulariCevaplari: "/genel-kultur-sorulari-ve-cevaplari",
  genelKulturTesti: "/genel-kultur-testi",
  genelKulturBilgiYarismasi: "/genel-kultur-bilgi-yarismasi",
  zorGenelKulturSorulari: "/zor-genel-kultur-sorulari",
  test50: "/50-soruluk-genel-kultur-testi",
  test100: "/100-soruluk-genel-kultur-testi",
  genelKulturBilgileri: "/genel-kultur-bilgileri",
  tarihSorulari: "/tarih-sorulari",
  tarihSorulariCevaplari: "/tarih-sorulari-ve-cevaplari",
  bilimSorulari: "/bilim-sorulari",
  bilimSorulariCevaplari: "/bilim-sorulari-ve-cevaplari",
  sanatSorulari: "/sanat-sorulari",
  sanatSorulariCevaplari: "/sanat-sorulari-ve-cevaplari",
  game: "/genel-kultur-oyunu",
  results: "/sonuclar",
  about: "/hakkimizda",
  contact: "/iletisim",
  privacy: "/gizlilik-politikasi",
  cookies: "/cerez-politikasi",
  contentPolicy: "/icerik-politikasi",
  adsDisclosure: "/reklam-bilgilendirmesi",
  terms: "/kullanim-kosullari",
  // AI Otomasyon Rotalari
  dailyList: "/gunluk-haberler",
  dailyLanding: "/test/:slug",
  dailyGame: "/test/:slug/oyna",
  // Ozgun rehber/blog icerikleri
  guides: "/genel-kultur-rehberi",
  guideDetail: "/rehber/:slug",
} as const;

export const LEGACY_ROUTES = {
  categories: "/categories",
  game: "/game",
  results: "/results",
  about: "/about",
  contact: "/contact",
  privacy: "/privacy",
  terms: "/terms",
} as const;
