/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-error": "#690005",
        "secondary-fixed-dim": "#acc7ff",
        "secondary-fixed": "#d7e2ff",
        "surface-container-lowest": "#010e24",
        "on-surface": "#d6e3ff",
        "primary-fixed": "#ffe088",
        "on-secondary": "#002e68",
        "surface-container-highest": "#27354c",
        "background": "#041329",
        "on-error-container": "#ffdad6",
        "on-secondary-fixed": "#001a40",
        "inverse-primary": "#735c00",
        "primary-container": "#d4af37",
        "on-tertiary-fixed-variant": "#005305",
        "on-primary-fixed-variant": "#574500",
        "inverse-surface": "#d6e3ff",
        "on-primary": "#3c2f00",
        "on-primary-fixed": "#241a00",
        "surface-tint": "#e9c349",
        "surface-dim": "#041329",
        "on-surface-variant": "#d0c5af",
        "surface-container-low": "#0d1c32",
        "on-secondary-container": "#95b8ff",
        "surface": "#041329",
        "tertiary": "#71e862",
        "on-tertiary-fixed": "#002201",
        "on-primary-container": "#554300",
        "error-container": "#93000a",
        "outline": "#99907c",
        "secondary-container": "#1d4889",
        "surface-variant": "#27354c",
        "error": "#ffb4ab",
        "on-tertiary-container": "#005104",
        "on-secondary-fixed-variant": "#1a4586",
        "primary-fixed-dim": "#e9c349",
        "on-background": "#d6e3ff",
        "tertiary-fixed-dim": "#68df5b",
        "surface-container-high": "#1c2a41",
        "secondary": "#acc7ff",
        "inverse-on-surface": "#233148",
        "surface-container": "#112036",
        "tertiary-container": "#54cb49",
        "primary": "#f2ca50",
        "surface-bright": "#2c3951",
        "tertiary-fixed": "#85fd74",
        "outline-variant": "#4d4635",
        "on-tertiary": "#003a02"
      },
      fontFamily: {
        "headline": ["Inter"],
        "body": ["Inter"],
        "label": ["Inter"]
      },
      borderRadius: {"DEFAULT": "0.25rem", "lg": "0.5rem", "xl": "0.75rem", "full": "9999px"},
    },
  },
  plugins: [],
}
